### ISSUE TITLE
Error Building Serverimage while CodeStripping enabled

### ISSUE THREAD

**Issue by Cibrock** [FirstGearGames/FishNet#668]
**General**
Unity version: 2021.3.9.f1
Fish-Networking version: 3.11.18
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1238875816742617169

**Description**
While CodeStripping enable in the Fishnet Pro Version, if i want to Build a Linux Server Build(headless) i get an error for all Functions flagged with the [Client] Attribute.
Error Message:
Unity\VIAOnline\Assets\FishNet\CodeGenerating\cecil-0.11.4\Mono.Cecil\AssemblyWriter.cs(2224,5): error System.ArgumentException: Member 'System.Void CheckForCurserMode()' is declared in another module and needs to be imported

**Replication**
I dont really know ho to replicate this behaivior.

**Expected behavior**
Unitys buildprozess to complete succesfully without any Errormessages while CodeStripping enabled

**Comment by FirstGearGames** [comment]
We don't troubleshoot V3 anymore (except under special circumstances such as enterprise support). If this issue persist after upgrading to V4 follow-up here please.

**Comment by FirstGearGames** [comment]
Please let me know if this still persist in V4.

**Comment by FirstGearGames** [comment]
Closed due to inactivity.
