### ISSUE TITLE
Cannot compile if IReplicateData structs contain nullables

### ISSUE THREAD

**Issue by Yoraiz0r** [FirstGearGames/FishNet#281]
Unity version: 2021.3.7f1
Fish-Networking version: 3.5.1.Experimental.Pro

**Describe the bug**
I updated a FishNet project from 2.3.14 to 3.5.1, updated my reconcile and replicate messages to use the new provided interfaces, and witnessed that my project will not compile, with the error ```myprojectpathhere\Assets\FishNet\CodeGenerating\Helpers\Extension\TypeReferenceExtensions.cs(27,13): error System.NullReferenceException: Object reference not set to an instance of an object.```

After patching the above code with a null check, I got ```myprojectpathhere\Assets\FishNet\CodeGenerating\cecil-0.11.4\Mono.Cecil\AssemblyWriter.cs(2224,5): error System.ArgumentException: Member 'T System.Nullable`1::value' is declared in another module and needs to be imported```

The code that triggered this was the inclusion of nullables in my IReplicateData, that worked in 2.3.14
```
private struct RepInput : IReplicateData
        {
            public Vector2 Dirs;
            public Vector3? TargetPosition;
            public Vector3? NextTargetPosition;
            public Vector3? NextTargetPosition2;

            private uint _tick;
            public uint GetTick() => _tick;

            public void SetTick(uint value) => _tick = value;

            public void Dispose()
            {
            }
        }
```

**To Reproduce**
1. Create an IReplicateData struct
2. Include a nullable such as `Vector3? SomeField;`
3. See compilation error

**Expected behavior**
FishNet.3.5.1.Experimental.Pro should be able to serialize nullables without errors.

**Comment by FirstGearGames** [comment]
Confirmed. Fix order set to priority.

**Comment by FirstGearGames** [comment]
After investigation it would seem this is caused by 3x unable to properly create comparers for the nullable types.
Comparers in prediction datas are important as this is a huge optimization on what's sent/resend by avoiding duplicates.

Version 2x did not use comparers, which is why it did not have problems; data was just always sent.

Automating this check is a considerable amount of work and not something I can put time towards right now. I will instead let users create their own comparers, much like custom writers.
It will look something like this...

```cs
    public static bool CompareNullableV3(Vector3? a, Vector3? b)
    {
        //One is null while the other is not.
        if ((a is null) != (b is null))
            return false;
        //Both are null.
        if (a is null && b is null)
            return true;

        //If here both must have value.
        return (a.Value == b.Value);
    }
```

**Comment by FirstGearGames** [comment]
Confirmed working in 3.5.2.

Replicate structure...
```cs
    private struct RepInput : IReplicateData
    {
        public float Speed;
        public Vector3? TargetPosition; 

        private uint _tick;
        public uint GetTick() => _tick;
        public void SetTick(uint value) => _tick = value;
        public void Dispose() { }
    }
```

Generated comparer code...
```cs
		// Token: 0x0600002B RID: 43 RVA: 0x0000261C File Offset: 0x0000081C
		public static bool Comparer___PredictedNullableFIelds_Break/RepInput(PredictedNullableFields_Break.RepInput value0, PredictedNullableFields_Break.RepInput value1)
		{
			return value0.Speed == value1.Speed && PredictedNullableFields_Break.CompareNullableVector3(value0.TargetPosition, value1.TargetPosition);
		}
```
